// let DOM elemnts
let $game = document.querySelector('#game')
let $start = document.querySelector('#start')
let $timeHeader = document.querySelector('#time-header')
let $resultHeader = document.querySelector('#result-header')
let $result = document.querySelector('#result')
let $time = document.querySelector('#time')
let gameTimeShow = document.querySelector('#game-time')
let score = 0
let isGameStarted = false